### ISSUE TITLE
Create a Long Term Storage Script

### ISSUE THREAD

**Issue by NMcKittie** [ayeshaa63/c10-lmnh-plants-project#10]
## Description

- This script is to extract and delete the out-of-date data from the database and puts it into long-term storage in an S3 bucket. The output file format will be a CSV.

## Relevant Files

N/A

## User Stories

- "The user only wants data from the last 24 hours in the database, the rest should be in long-term storage."

**Comment by hhm970** [comment]
Finished the script; it will not filter for similar recordings. This could be an added functionality for the future
