### ISSUE TITLE
Write tests for load script

### ISSUE THREAD

**Issue by hhm970** [ayeshaa63/c10-lmnh-plants-project#24]
## Description

Create unit testing to ensure the quality of code and that bugs are spotted early. Unit testing may involve mocking the database.

## Relevant Files

- pytest
- pytest-cov
- load.py
- conftest.py
- test_load.py

## User Stories

As an engineer, we need tests to ensure our code is working!

**Comment by DKWeeto** [comment]
Tests are passing, more to write in future
