### ISSUE TITLE
Create high level plan

### ISSUE THREAD

**Issue by NMcKittie** [ayeshaa63/c10-lmnh-plants-project#5]
## Description

Create a high-level plan for the project before beginning. Involves making decisions and creating diagrams to map those decisions. This also involves assigning tasks to group members.

## User Stories

- "As an engineer, I want a clear plan for the project so I know what I am doing and what my teammates are doing. This will help me to do my work smoothly."

**Comment by DKWeeto** [comment]
We have a plane
