### ISSUE TITLE
Create a Load Script

### ISSUE THREAD

**Issue by NMcKittie** [ayeshaa63/c10-lmnh-plants-project#9]
## Description

- Take the Dataframe returned from transform.py and upload it into short-term memory.
- Short-term memory will be a database hosted by Microsoft SQL Server.

## Relevant Files

- extract.py
- transform.py
- Dockerfile

## User Stories

- "As a user, I want the latest plant information to be easily accessible within a database to enable efficient and relevant dashboard information."

**Comment by DKWeeto** [comment]
Load script has been created and apparently runs smoothly
